name: Makefile CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.23
      uses: actions/setup-go@v7
      with:
        go-version: '1.23'
      id: go
    - uses: actions/checkout@v7
    - name: Run fmt-check
      run: make fmt-check
    - name: Run golangci-lint
      run: make lint
    - name: Run go test
      run: make test
