name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run build-amd64-bin
        run: make build GOOS=linux GOARCH=amd64

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          body: See the [CHANGELOG](https://github.com/loggie-io/loggie/blob/${{ github.ref }}/doc/changelog/CHANGELOG-v1.md) for more details.
          draft: false
          prerelease: false
          files: |
            loggie
